version: "3.7"

services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
